//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceDMO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDMO.IDMOService")]
    public interface IDMOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/GetProductsList", ReplyAction="http://tempuri.org/IDMOService/GetProductsListResponse")]
        wcf_19Aralik2017DMOLibrary.ProductDTO[] GetProductsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/GetProductsList", ReplyAction="http://tempuri.org/IDMOService/GetProductsListResponse")]
        System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.ProductDTO[]> GetProductsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/GetOneProduct", ReplyAction="http://tempuri.org/IDMOService/GetOneProductResponse")]
        wcf_19Aralik2017DMOLibrary.ProductDTO GetOneProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/GetOneProduct", ReplyAction="http://tempuri.org/IDMOService/GetOneProductResponse")]
        System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.ProductDTO> GetOneProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/ProductUpdate", ReplyAction="http://tempuri.org/IDMOService/ProductUpdateResponse")]
        bool ProductUpdate(wcf_19Aralik2017DMOLibrary.ProductDTO pdto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/ProductUpdate", ReplyAction="http://tempuri.org/IDMOService/ProductUpdateResponse")]
        System.Threading.Tasks.Task<bool> ProductUpdateAsync(wcf_19Aralik2017DMOLibrary.ProductDTO pdto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/Login", ReplyAction="http://tempuri.org/IDMOService/LoginResponse")]
        wcf_19Aralik2017DMOLibrary.UserDTO Login(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/Login", ReplyAction="http://tempuri.org/IDMOService/LoginResponse")]
        System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.UserDTO> LoginAsync(int id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/GetProductsListBySupplierId", ReplyAction="http://tempuri.org/IDMOService/GetProductsListBySupplierIdResponse")]
        wcf_19Aralik2017DMOLibrary.ProductDTO[] GetProductsListBySupplierId(int suppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMOService/GetProductsListBySupplierId", ReplyAction="http://tempuri.org/IDMOService/GetProductsListBySupplierIdResponse")]
        System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.ProductDTO[]> GetProductsListBySupplierIdAsync(int suppID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDMOServiceChannel : WebClient.ServiceDMO.IDMOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMOServiceClient : System.ServiceModel.ClientBase<WebClient.ServiceDMO.IDMOService>, WebClient.ServiceDMO.IDMOService {
        
        public DMOServiceClient() {
        }
        
        public DMOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wcf_19Aralik2017DMOLibrary.ProductDTO[] GetProductsList() {
            return base.Channel.GetProductsList();
        }
        
        public System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.ProductDTO[]> GetProductsListAsync() {
            return base.Channel.GetProductsListAsync();
        }
        
        public wcf_19Aralik2017DMOLibrary.ProductDTO GetOneProduct(int id) {
            return base.Channel.GetOneProduct(id);
        }
        
        public System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.ProductDTO> GetOneProductAsync(int id) {
            return base.Channel.GetOneProductAsync(id);
        }
        
        public bool ProductUpdate(wcf_19Aralik2017DMOLibrary.ProductDTO pdto) {
            return base.Channel.ProductUpdate(pdto);
        }
        
        public System.Threading.Tasks.Task<bool> ProductUpdateAsync(wcf_19Aralik2017DMOLibrary.ProductDTO pdto) {
            return base.Channel.ProductUpdateAsync(pdto);
        }
        
        public wcf_19Aralik2017DMOLibrary.UserDTO Login(int id, string pass) {
            return base.Channel.Login(id, pass);
        }
        
        public System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.UserDTO> LoginAsync(int id, string pass) {
            return base.Channel.LoginAsync(id, pass);
        }
        
        public wcf_19Aralik2017DMOLibrary.ProductDTO[] GetProductsListBySupplierId(int suppID) {
            return base.Channel.GetProductsListBySupplierId(suppID);
        }
        
        public System.Threading.Tasks.Task<wcf_19Aralik2017DMOLibrary.ProductDTO[]> GetProductsListBySupplierIdAsync(int suppID) {
            return base.Channel.GetProductsListBySupplierIdAsync(suppID);
        }
    }
}
